mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cbhx.dao.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
    local-date-time-format: yyyy-MM-dd HH:mm:ss