server:
  port: 8080

spring:
  application:
    name: CBHX
  profiles:
    active: datasource,swagger,mybatis
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
