spring:
  datasource:
    url: jdbc:mysql://10.24.67.173:3307/cbhx?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dataquality
    password: Os@1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource